[build]
  functions = "functions"
[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"
# Basic-Auth allows you to password protect your whole site.
Basic-Auth = "ameer:ameer123" 
